_targets/build.project.armv7m4-stm32l4x6
```
${PROGS}/psh
```
Clearly shows than `PROGS` is directory.
Other changes:
- changed the script header.
- redundant double quotes have been removed
=> stm32l4x6: small code changes in the build script

.github/actions/phoenix-build/action.yml, .github/workflows/ci.yml, README.md, _targets/build.project.armv7a7-imx6ull, _targets/build.project.armv7m4-stm32l4x6, _targets/build.project.armv7m7-imxrt106x, _targets/build.project.ia32-generic, _targets/build.project.riscv64-spike, _targets/build.project.riscv64-virt, build.project, docker-build.sh
**WORK IN PROGRES | DO NOT MERGE**
This PR includes many buildscript enhancements and fixes to make it possible building with docker environment.
This also adds github workflow to automatically test building for supported targets (experimental).
=> Build enhancements

_targets/build.project.ia32-generic, docker-build.sh
- fix creating ia32-generic image, speed it up by writing bigger chunks of data
- bind share as `:delegated`
- hackish: use tmpfs for intermediate build artifacts (I/O operations on bind mounts on Darwin are painfully slow)
=> Enhancements for docker on macOS

docker-build.sh
This fixes GH-30 for Darwin host platform.
=> build: docker: fix mounting tmpfs without executable permission

.gitmodules, _targets/build.project.riscv64-spike, _targets/build.project.riscv64-virt, build.project
This PR adds opensbi bootloader for RISCV64 and introduces following changes:
1. moved riscv-pk submodule to riscv/riscv-pk (opensbi submodule is placed at the same level in riscv/opensbi),
2. added RISCV64 loader selection with RISCV_LOADER variable:
- RISCV_LOADER="bbl" -> use bbl as bootloader, generate .bbl kernel image,
- RISCV_LOADER="opensbi" -> use opensbi as bootloader, generate .osbi kernel image,
- RISCV_LOADER equals anything else -> no bootloader, use flat kernel binary .bin image,
Appropriate kernel image is saved in _boot/ folder when running build.sh script with 'image' or 'all' options ('image' option creates _boot/ folder).
=> riscv64: added opensbi bootloader

_targets/build.project.armv7m7-imxrt106x
Substitute non-portable `stat -c "%s" $1` with `wc -c < $1`.
Fixes #40.
=> imxrt106x: Fix buildling on MacOS

_targets/build.project.ia32-generic
Change is supposed to make possible building plo and kernel in serial mode by setting variable explicitly:
TARGET=ia32-generic CONSOLE=serial phoenix-rtos-build/build.sh ...
Referenced by:
https://github.com/phoenix-rtos/plo/pull/25
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/175
=> Allow setting CONSOLE variable without overwriting it

scripts/qemu/ia32-generic-ata.sh, scripts/qemu/ia32-generic-rtl.sh, scripts/qemu/ia32-generic-vblk.sh, scripts/qemu/ia32-generic-vgpu.sh, scripts/qemu/ia32-generic-vnet.sh, scripts/qemu/ia32-generic.sh, scripts/qemu/riscv64-virt-vblk.sh, scripts/qemu/riscv64-virt-vgpu.sh, scripts/qemu/riscv64-virt-vnet.sh, scripts/qemu/riscv64-virt.sh
Added scripts allow to easily run Phoenix-RTOS image under QEMU with additional devices and options (e.g. with attached virtio devices). The general idea is to create a wrapper scripts for QEMU startup command. Each QEMU emulated target (ia32-generic and riscv64-virt for now) has a main startup script named 'target.sh' (e.g. ia32-generic.sh for ia32-generic target). The main script extends default qemu startup command with additional options which simplify device creation (e.g. -vblk, -vgpu or -vnet). One can still pass in original qemu options like -cpu, -smp or -kernel. There are also additional scripts named 'target-dev.sh'  which attach specific device to default system configuration (e.g. ia32-generic-vblk.sh runs default ia32-generic Phoenix-RTOS image with extra virtio-blk devices …
=> Added scripts to simplify running Phoenix-RTOS on QEMU (JIRA: PD-20)

_targets/build.project.armv7a7-imx6ull, _targets/build.project.armv7a9-zynq7000, _targets/build.project.armv7m4-stm32l4x6, _targets/build.project.armv7m7-imxrt106x, _targets/build.project.armv7m7-imxrt117x, _targets/build.project.ia32-generic, _targets/build.project.riscv64-spike, _targets/build.project.riscv64-virt, _user/Makefile, _user/hello/Makefile, _user/hello/main.c
The main goal of this PR is to simplify usage of phoenix-rtos-project.
It contains the following changes:
1. **_user** - directory contains user applications and is built for each platform; output binaries are located in _/root/userbin_
2. For `imxrt106x`, `imxrt117x` and `zynq-7000`, programs are added to plo's script only if variable `TARGET_PROJECT` is empty.
3. One option is to add building of **_user** to each of the scripts in **phoenix-rtos-build/build-core-***. In this scenario **_user** is built each time.
4. The other approach is to create **_project** directory contains files for each for the platform, like `build.project-*-*-user` and there would be located building of **_user**. In this case, **_user** directory is built only for specific target.
**BEFORE MERGE:** Options 3 …
=> project: add example of user app

_targets/build.project.armv7a7-imx6ull, _targets/build.project.armv7m4-stm32l4x6, _targets/build.project.armv7m7-imxrt106x, _targets/build.project.armv7m7-imxrt117x, _targets/build.project.ia32-generic, _targets/build.project.riscv64-spike, _targets/build.project.riscv64-virt
defuser password hash is added to each target using psh for testing of login feature in psh.
Hash corresponds to password: 1234
JIRA: PD-75
=> psh: add defuser hash in _targets

_targets/build.common.imxrt, _targets/build.project.armv7m7-imxrt106x
Preinit script for plo located in ram cannot call user script.
=> common.imxrt: create different preinit script for plo located in ram

docker-build.sh
Change needed because new docker image will contain libphoenix
(libraries and headers) owned by root (cp -a refuses to preserve file
attrs if You're not the owner of the file).
Added separate step to fix file permissions in _boot (probably hardly
ever needed).
Needed because of: 
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/113
- https://github.com/phoenix-rtos/phoenix-rtos-docker/pull/3
=> docker-build: build as root in container and fix permissions afterwards

_targets/build.project.armv7m7-imxrt106x, _targets/build.project.armv7m7-imxrt117x
For `imxrt106x`, current FlexRAM setup is `0xaabfffff` ([_init.S](https://github.com/phoenix-rtos/plo/blob/75e3f82897df2649d8b7d1b2e69120d6275ec02f/hal/armv7m/imxrt/10xx/_init.S#L191)):
* `dtcm` =5*32kB (160kB),
* `itcm`: 11*32kB (352kB),  *`itcm` map end address was adjusted to `0x58000`*
Adding peripherals mapping `AIPS1-4`, `AIPS-5` and FlexSPI memory map.
This setup was tested on evk-imxrt1064 and is the minimum required to enable MPU with `dummyfs`, `imxrt-multi` and `psh`.
The activation of MPU has been tested on evk-imxrt1064 target.
For `imxrt-117x`, adjust the alignment of `ocram2` to 512*1024 to make the pre-setting of MPU regions and memory maps in `plo` work. The activation of MPU has not been tested on imxrt117x target.
JIRA: RTOS-2
Update project to recent changes in `plo` …
=> Update map setup (MPU plo)

_targets/build.common, _targets/build.project.armv7m7-imxrt106x, _targets/build.project.armv7m7-imxrt117x, _targets/build.project.ia32-generic
Changed not portable parts of building scripts.
Fixes build on MacOS.
[JIRA: CI-70](https://jira.phoenix-rtos.com/browse/CI-70)
=> Fix building on MacOS

_targets/build.project.armv7a7-imx6ull
JFFS2 summary nodes make rootfs to be mounted 2-4x times faster.
Reintroduced from INC.
JIRA: DTR-104
=> imx6ull: add summary nodes creation to JFFS2 image

_targets/build.project.armv7m7-imxrt117x
Changing the default kernel and apps upload method from `com1` to `usb0` for the `imxrt1170` target. From that moment the uploading method becomes the same as `imxrt1064`  which means the method is unified for both targets.
JIRA: RTOS-99
Enable faster than upload on imxrt1170 target.
=> imxrt1176: replace default upload method with usb0

_targets/build.project.armv7a9-zynq7000
1. Map definition was updated. The kernel is loaded to `kddr` and programs are loaded to `ddr` map.  The kernel allocates some additional memory above `.bss` section. In the previous configuration, plo has loaded programs in memory above kernel what caused that programs have been overwritten.
2. In order to run Phoenix-RTOS on qemu the plo has to be loaded into `OCRAM`. Copy of plo image without boot layout is copied into `_boot` directory. @agkaminski , unfortunately there will be two files, I remember our previous discussion ;) 
JIRA: PD-203
=> zynq7000: update preinit script and copy plo image to be reusable on qemu

_targets/build.project.armv7a9-zynq7000, scripts/armv7a9-zynq7000.sh
- fix file checking condition
- move flash image creation to build process
JIRA: PD-203
=> scripts/zynq7000: move flash image creation to build process

_targets/build.project.armv7m7-imxrt117x
JIRA: RTOS-128
This commit changes the board setup for imxrt117x target to be able to run on MIMXRT1170-EVK by default.
Required submodules are also updated with this commit:
* plo d9d621d...f540178 (2):
> flash-imxrt: fix chip erase for Winbond and Micron
> flash-imxrt: add ISSI nor flash lookup table
=> Update submodules and make MIMXRT1170-EVK default board for imxrt117x target

_targets/build.project.armv7a7-imx6ull
Added option not to write jffs2 cleanmarkers to NAND jffs2 image.
NAND cleanmarkers are written to metadata area.
[JIRA: DTR-244](https://jira.phoenix-rtos.com/browse/DTR-244)
=> _targets/armv7a7-imx6ull: don't write cleanmarkers when creating NAND jffs2 rootfs image

_targets/build.project.armv7a7-imx6ull
JIRA: RTOS-157
_targets: imx6ull: load psh in UPLOAD_SCRIPT
Make running Phoenix-RTOS on imx6ull-evk possible and update quickstart for this platform. The current version of quickstart was adapted to feature/syspage with plo for imx6ull, which isn't available now.
=> _targets: imx6ull: load psh in UPLOAD_SCRIPT

_targets/build.project.armv7m7-imxrt106x, _targets/build.project.ia32-generic
JIRA: PD-189
Adding micropython environment variable in build configurations of:
- ia32-generic (default to `yes`)
- imxrt106x (default to 'no')
As phoenix-rtos supports micropython it should be enabled, or at least mentioned in tested target build configurations
=> _targets: add micropython environment variable

_fs/root-skel/etc/rc.psh, _targets/build.project.ia32-generic
- modify /etc/rc.psh to run psh after lwip and posixsrv start
- enable running /etc/rc.psh in loading script for ia32-generic target
It may be useful, for example when running busybox test suite (JIRA: RTOS-59)
=> run rc.psh on startup for ia32-generic target

scripts/ia32-generic-test.sh, scripts/ia32-generic.sh, scripts/ia32-virt.sh
1) scripts: add ia32-generic script with net setup for testing purposes
2) scripts: ia32-generic: set cpu to supported pentium3
1) JIRA: CI-116
2) JIRA: PD-251
1) The main purpose is to enable proper lwip launching in CI process by updating qemu running command.
Now the command for running qemu (ia32-generic target) is now placed strictly in test runner:
It may be better to create the proper script in `scripts` directory that could be used by a test runner. If there is a need for change in qemu running it will be done only in the `scripts` directory (it's easier to remember about changing similar script in the same directory than changing some file in tests repository).
2) When some ca-certificates are used by openssl, sse2 instructions may be executed.
Openssl firstly checks wheather an …
=> scripts: add ia32-generic script with net setup for testing purposes, specifying pentium3 cpu in all scripts

.github/actions/phoenix-build/action.yml, .github/workflows/ci-submodule.yml, .github/workflows/lint.yml
Maintain single copy of CI submodule workflow instead of multiple ones.
Won't work without changes in `phoenix-rtos-build`.
JIRA: CI-14
=> ci: use reusable workflows in submodules

.github/workflows/ci-submodule.yml
- ci: add secrets inputs to ci-submodule reusable workflow
JIRA: CI-119
Mailing from submodules actions stopped working after adding reusables. Secrets have to be passed for each call to fix it.
=> ci: add secrets inputs to ci-submodule reusable workflow

_targets/build.project.armv7a9-zynq7000
JIRA: PP-38
Add bistream to the flash image. Create two bash variables (BS_OFFS and BS_SZ) which allow to create plo alias of bitstream on flash.
=> zynq7000: Add optional bitstream in flash img. Change flash layout

_targets/build.project.riscv64-generic
Added `phoenix.disk` image as image build artifact. Required by qemu startup script.
[JIRA: RTOS-201](https://jira.phoenix-rtos.com/browse/RTOS-201)
=> _targets/riscv64-generic: generate phoenix.disk image artifact

_projects/armv7a7-imx6ull-evk/build.project, _projects/armv7a9-zynq7000-qemu/build.project, _projects/armv7a9-zynq7000-zedboard/build.project, _projects/armv7a9-zynq7000-zturn/build.project, _projects/armv7m4-stm32l4x6-nucleo/build.project, _projects/armv7m7-imxrt105x-evk/build.project, _projects/armv7m7-imxrt106x-evk/build.project, _projects/armv7m7-imxrt117x-evk/build.project, _projects/host-generic-pc/build.project, _projects/ia32-generic-pc/build.project, _projects/ia32-generic-qemu/build.project, _projects/riscv64-generic-qemu/build.project, _projects/riscv64-generic-spike/build.project, build.project
Restored sourcing target file (`_targets/build.project.$TARGET_FAMILY-$TARGET_SUBFAMILY`) in the main `build.project` so that the project file (`_projects/$TARGET/build.project`) no longer needs to do this.
[JIRA: RTOS-202](https://jira.phoenix-rtos.com/browse/RTOS-202)
=> build.project: restore sourcing target file

_targets/build.common
JIRA: SKAL-561
For armv7m4-stm32l4x6 targets we would like to do bankswitch on firmware upgrade to remap flash banks. This addition allows common scripts to emit those command for plo preinit scritp by defining BAKSWITCH variable.
=> build.common: Allow bankswitch for firmware upgrade

_projects/ia32-generic-pc/board_config.h, _projects/ia32-generic-qemu/board_config.h, _projects/riscv64-generic-qemu/board_config.h, _projects/riscv64-generic-spike/board_config.h
This changes need additional PR in `phoenix-rtos-devices` to work properly.
PP-82
`uart16550` is used by zynq7000 and either baudrate and console have to be configurable.
=> projects/ia32-generic & riscv64: add UART16550 configuration to board_config.h

.github/actions/phoenix-build/action.yml, .github/workflows/ci-submodule.yml
This change will make compilation warnings/errors visible inline in PRs,
for example: https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/81/files
JIRA: CI-147
Too many times new compilation warnings were added to our codebase by accident.
=> ci: change submodule build to out-of-tree for problemMatchers to work

.github/workflows/ci-submodule.yml, .github/workflows/ci.yml, .github/workflows/lint.yml
JIRA: CI-151
Remove extra warnings from CI
=> ci: switch to node16 actions due to GH deprecating node12

_projects/armv7a9-zynq7000-qemu/build.project, _projects/armv7a9-zynq7000-zedboard/build.project, _projects/armv7a9-zynq7000-zturn/build.project, _targets/build.project.armv7a9-zynq7000
This change decrease time startup of the system with rootfs.
If the file contains 0xff in empty spaces and cleanmarkers, the jffs2 performs less read operation at the begining.
details:
- writing cleanmarkers is added as an option
- jff2 image contains padding at the end of the final erase block
RTOS-269
=> _targets/zynq7000: modify jffs2 image, add cleanmarkers and padding

_targets/build.common
JIRA: SKAL-681
This change causes that elf aliases are stored in plo script without allignment. In plo app command calls syspage_entryAdd with SIZE_PAGE. alignment, so loaded  application shouldn't be placed in map holes.
Result of plo "map" cmd before and after change on armv7mr-stm32l4x6-nucleo:
Before:
```
(plo)% map                                                                      
ID   NAME     START          END            ATTR
0    flash0   0x08000000     0x08080000     rx
0x0800d000     0x0801c400   - allocated
0x0801c400     0x08027400   - allocated
0x08027400     0x0803e600   - allocated
-------------------------
1    flash1   0x08080000     0x08100000     rx
2    ram      0x20000000     0x20050000     rwx
0x20000000     0x20001200   - allocated
0x20010000     0x20010410   - …
```
=> build.common: pass not aligned sizes to plo script

.github/workflows/lint.yml
GA ubuntu-latest image was upgraded to 22.04 LTS, clang-format-diff-10 is no longer present.
JIRA: CI-159
=> ci: upgrade to clang-format-12

_projects/armv7a7-imx6ull-evk/build.project, _targets/build.project.armv7a7-imx6ull
JIRA: RTOS-398
boot from plo on nor flash.
* phoenix-rtos-doc 4eaac00...5d1f42a (3):
> libc: add getopt, getpgid, getsid, memccpy, setenv, strncpy, truncate
> libc: documentation correction
> imx6ull: boot from nor (#139)
* phoenix-rtos-hostutils 853e232...a56b518 (1):
> imx6ull: boot from qspi nor flash
* plo 315360b...42bc591 (4):
> imx6ull: flash nor driver over qspi
> flash-imx6ull: Add optional logic to perform big buffer read.
> cmds: implement test-dev
> imx6ull: boot from qspi nor flash
imx6ull lacks support for starting from flash
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/378
https://github.com/phoenix-rtos/plo/pull/231
https://github.com/phoenix-rtos/plo/pull/236
https://github.com/phoenix-rtos/phoenix-rtos-hostutils/pull/42 …
=> imx6ull: boot from plo on nor flash

_targets/build.common, _targets/build.project.armv7a7-imx6ull, _targets/build.project.riscv64-generic
It's done to avoid using host readelf, which may be incompatible (especially on macOS) with gcc version currently supported on Phoenix-RTOS.
JIRA: CI-332
=> _targets: switch to {cross}readelf

_targets/build.project.riscv64-generic, mtd-utils/build.sh
JIRA: CI-334
`TOPDIR` was obsoleted in favor of `PREFIX_PROJECT`
=> build: remove TOPDIR usage

_targets/build.project.riscv64-generic, scripts/riscv64-generic-qemu.sh, scripts/riscv64-generic-spike.sh
The change fixes the regex incorrectly matching multiple occurrences of the section names `*_start` (should match once, `_start` exactly). The fix is to add a blank match before the section names.
With `build.sh` use `host` component  which is required to build `syspagen` (CI fails because of no `host` [component in default buld params](https://github.com/phoenix-rtos/phoenix-rtos-project/blob/master/.github/workflows/ci-project.yml#L16)?).
Update: This PR adds `host` to CI https://github.com/phoenix-rtos/phoenix-rtos-project/pull/821
JIRA: RTOS-592
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/819
=> targets: fix regex matching syspage sections on riscv64

_targets/build.project.armv7m4-stm32l4x6
JIRA: DEND-32
Remove exported BOARD_CONFIG
It overwrites board_config.h and make confusion. Not needed for internal project - rest of removal deprecated BOARD_CONFIG expoted variable removal will be performed in others commits. 
Project that use fork of phoenix-rtos-project and use BOARD_CONFIG env variable, need to be switched to board_config.h 
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/422
Updates submodules with that commit first
=> _targets: stm32l4x6: Remove exported BOARD_CONFIG

_projects/armv7m7-imxrt105x-evk/board_config.h, _projects/armv7m7-imxrt106x-evk/board_config.h, _projects/armv7m7-imxrt117x-evk/board_config.h, _projects/sparcv8leon3-gr716-mini/board_config.h
Change enables pseudo devices in multi-driver on imxrt10xx, imxrt117x
and sparcv8leon3-gr716-mini.
Note: if posixsrv is to be used libpseudodev needs to be disabled.
JIRA: RTOS-640
* phoenix-rtos-devices ee66265..acd572c:
> gr716-multi: add support for pseudo devices
> imxrt-multi: add support for pseudo devices
> Introduce library for handling pseudo devices
> imx6ull-uart: apply MISRA
> libtty/lf_fifo: drop old bytes in case of overrun
JIRA: RTOS-640
=> Update submodule enabling pseudo devices

.github/workflows/ci-project.yml, .github/workflows/ci-submodule.yml
If one of matrix jobs fails (e.g., for one specific target), the other matrix jobs will continue running and will not be cancelled
Stopping jobs on targets, even if one has failed, makes it difficult to identify errors, especially if there are intermittent issues with a particular target.
=> ci: ensure jobs continue even if one fails

_projects/armv7m7-imxrt117x-evk/build.project
Adds watchdog variable in imxrt117x target. Watchdog support was merged in this PR:
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/467
JIRA: RTOS-657
=> imxrt117x: add watchdog

_projects/armv7a7-imx6ull-evk/rootfs-overlay/etc/rc.psh, _projects/armv7a9-zynq7000-qemu/rootfs-overlay/etc/rc.psh, _projects/armv7a9-zynq7000-zedboard/rootfs-overlay/etc/rc.psh, _projects/armv7a9-zynq7000-zturn/rootfs-overlay/etc/rc.psh, _projects/ia32-generic-pc/rootfs-overlay/etc/rc.psh, _projects/ia32-generic-qemu/rootfs-overlay/etc/rc.psh
On targets `ia32-generic`, `armv7a9-zynq7000`, `armv7a7-imx6ull` add exports for the following variables:
* PATH=/bin:/sbin:/usr/bin:/usr/sbin (supported by 'execvpe')
* HOME=/root (supported by 'cd' command)
JIRA: RTOS-682
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/202
https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/299
=> Add PATH support to rc.psh and runfile

_targets/build.project.armv7a7-imx6ull, _targets/build.project.armv7a9-zynq7000
Changed page size parameter when building root FS for Zynq 7000 systems.
Previously the page size parameter was set to flash chip page size of 256 bytes instead of the system memory page size of 4096 bytes. Now the page size is set correctly.
This change improves filesystem performance, especially on armv7a9-zynq7000-qemu (where filesystem mounting is now about 33% faster). Additionally, the resulting filesystem image is smaller.
=> zynq7000: Set page size correctly in mkfs.jffs2

_projects/ia32-generic-pc/rootfs-overlay/etc/rc.psh, _projects/ia32-generic-qemu/rootfs-overlay/etc/rc.psh, _targets/build.project.ia32-generic
Use dummyfs to create `devfs` and mount it in `/dev` directory.
With this change `devfs` can be used to access devices on ia32-generic the same way as on other platforms.
=> ia32-generic: Mount dummyfs in /dev

.github/problem-matchers/gcc.json, .github/workflows/ci-project.yml, .github/workflows/ci-submodule.yml, .github/workflows/lint.yml
(do not merge with the top commit present)
- ci: use internal problem matcher for gcc
don't depend on external GH action as it's not needed.
- ci: migrate to actions based on node20
Needed due to node16 being EOLed.
JIRA: CI-398
=>  ci: migrate to actions based on node20

_projects/armv7m7-imxrt105x-evk/board_config.h, _projects/armv7m7-imxrt106x-evk/board_config.h, _projects/armv7m7-imxrt117x-evk/board_config.h
Enable `libposixsrv` on i.MX `RT1176` and `RT1064` by default, keep `libpseudodev` on i.MX `RT1052` due to low amount of ram.
JIRA: RTOS-641
=> imxrt: enable libposixsrv on rt1167, rt1064

scripts/riscv64-generic-qemu.sh
Restore `-serial stdio` QEMU flag. Needed to provide ability to interact through control codes with QEMU through our test runner.
=> riscv64-qemu: restore `-serial stdio` option

_user/serverdemo/main.c
* libphoenix fed7350...10af1b0 (5):
> riscv64/reboot: fix include path
> unistd/alarm: update `tid` type
> !sys/interrupt: update function signature
> clean up includes
> riscv64: add system reset handling
* phoenix-rtos-build 14a4a73...132890f (1):
> host-generic: install kernel headers
* phoenix-rtos-corelibs 25343d8...3ec9db3 (2):
> libstorage: use off_t instead of offs_t
> update installed headers include path
* phoenix-rtos-devices 7f980d4...ac27d41 (5):
> dma: imx6ull, imxrt: fix handle type in `sdma_init`
> multiple files: use off_t instead of offs_t
> update installed headers include path
> imxrt-multi: disallow CM4 lockup to reset system
> imxrt-multi: add CM4 core reset
* phoenix-rtos-filesystems 5d26712...8af595a (1):
> multiple files: use off_t instead of offs_t
* …
=> update installed headers, update submodules

.github/workflows/ci-project.yml, .github/workflows/ci-submodule.yml
CI fails on host due to:
https://github.com/actions/runner-images/issues/9491
https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1032
*NOTE: This change is going to be active after merge to master
=> ci: decrease aslr entropy before testing and building on gh hosted runners

_projects/armv7m7-imxrt105x-evk/board_config.h, _projects/armv7m7-imxrt106x-evk/board_config.h, _projects/armv7m7-imxrt117x-evk/board_config.h
JIRA: RTOS-771
Adapts eval kits' project files to changes in phoenix-rtos/phoenix-rtos-devices#468 to avoid warnings and provide defaults/list of available defines.
=> _projects: Provide full mux config (+defaults) for imxrt eval kits

.github/workflows/ci-release.yml, .github/workflows/ci.yml
=> ci: run full campaign for every commit on release branch

_targets/build.common
This is needed to enable `nounset` option in `build.sh`: https://github.com/phoenix-rtos/phoenix-rtos-build/pull/184
=> add defaults to optional vars in _targets/build.common

_targets/build.project.armv7m4-stm32l4x6, _targets/build.project.armv7m7-imxrt105x, _targets/build.project.armv7m7-imxrt106x, _targets/build.project.armv7m7-imxrt117x
=>  armv7m: Update memory maps configuration to enable MPU 

_projects/armv8m33-mcxn94x-frdm/board_config.h, _projects/armv8m33-mcxn94x-frdm/build.project, _targets/build.project.armv8m33-mcxn94x
JIRA: RTOS-881
https://github.com/phoenix-rtos/plo/pull/337
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/222
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/569
https://github.com/phoenix-rtos/phoenix-rtos-hostutils/pull/55
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/132
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/508
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/195
https://github.com/phoenix-rtos/libphoenix/pull/371
=> Add armv8m33-mcxn94x-frdm target

_targets/build.project.armv8r52-mps3an536, scripts/armv8r52-mps3an536-qemu.sh
=> armv8r52-mps3-an536: copy plo elf to _boot directory

_targets/build.common
JIRA: RTOS-898
Check `plo` size and `OFFS_USER_SCRIPT` to not silently overwrite `plo` in phoenix disk.
=> _targets/build.common: add OFFS_USER_SCRIPT check

scripts/armv7a9-zynq7000-qemu-test.sh
JIRA: CI-397
In the process of creating a test that check's Control Codes, there is a problem with our QEMU setup. 
qemu-system-aarch64 with machine arm-generic-fdt-7series have multiple serials outputs. First one is responsible for VNC connection. Second one is strictly connected with emulated environment. Redirecting it to `mon:stdio` give us access to use QEMU shortcuts which they collide with our tests. Even in further use cases, this will be a problem.
Shortcuts available with serial output set on to `mon:stdio`:
To minimize interference from QEMU side, we can simply redirect serial directly on stdio and solve this problem.
=> armv7a9-qemu: Adjust serial device

_projects/armv7a9-zynq7000-zedboard/nvm.yaml, _projects/armv7a9-zynq7000-zedboard/user.plo.yaml
JIRA: CI-494
Currently patrition offsets in `trunner` are hardcoded thus slightly incorrect area was cleared (last 1MB of the partition might have had random data).
=> armv7a9-zynq7000-zedboard: fix rootfs partition offset

.github/workflows/ci-project.yml, .github/workflows/ci-submodule.yml
JIRA: CI-490
Should fix CI problems like
https://github.com/phoenix-rtos/phoenix-rtos-project/actions/runs/11378680528/job/31655243382
=> ci: improve compatibility with ubuntu-22.04 image

.github/workflows/lint.yml
Change shellcheck configuration to report errors only on added lines in PR (currently: whole files).
JIRA: CI-39
=> ci: shellcheck: report errors only in added lines

_projects/ia32-generic-pc/board_config.h, _projects/ia32-generic-qemu/board_config.h
=> _projects/ia32-generic-qemu: add pc-tty mouse/vdevs config options

_projects/ia32-generic-qemu/rootfs-overlay/etc/rc.psh, _targets/ia32/generic/build.project, _targets/ia32/generic/preinit.plo.yaml, _targets/ia32/generic/user.plo.yaml
JIRA: RTOS-998
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/533
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/636
https://github.com/phoenix-rtos/plo/pull/377
https://github.com/phoenix-rtos/libphoenix/pull/403
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/233
=> ia32: add option to run secondary psh

_fs/root-skel/etc/lighttpd.conf
lighttpd: lighttpd.conf updates
- prefer lighttpd defaults
- resource tuning
- remove mod_evasive and mod_usertrack (removed from upstream)
- comment out modules not otherwise used in lighttpd.conf
modern lighttpd with bug fixes and HTTP/2 (optional)
fixes issue blocking https://github.com/phoenix-rtos/phoenix-rtos-ports/pull/90
=> lighttpd: lighttpd.conf updates

_projects/armv8m33-mcxn94x-frdm/build.project
JIRA: RTOS-988
Add support for running RTOS on the CPU1
=> armv8m33-mcxn94x-frdm: Use CPU1

.gitignore
This project uses python packages like jinja2, there is a need for a separate directory to store virtual environment
=> .gitignore: add .venv dir to ignored

_projects/aarch64a53-zynqmp-qemu/board_config.h, _projects/aarch64a53-zynqmp-som/board_config.h
Added missing CAN driver configuration macros
JIRA: PP-272
=> zynqmp: add missing CAN config

_projects/aarch64a53-zynqmp-qemu/board_config.h, _projects/aarch64a53-zynqmp-som/board_config.h, _projects/aarch64a53-zynqmp-zcu104/board_config.h, scripts/aarch64a53-zynqmp-qemu.sh
Fix building of ZynqMP projects (added missing configuration macros)
- ZCU104 evaluation board (both building project and running it on board)
- SOM (building of aarch64a53-zynqmp-som), 
- QEMU (both build and running on qemu)
=> zynqmp: fix build - add missing uart16550 config

_projects/armv7a7-imx6ull-evk/build.project, _projects/armv7m7-imxrt106x-evk/build.project, _projects/armv7m7-imxrt106x-evk/lwip/lwipopts.h, _targets/armv7m7/imxrt106x/user.plo.yaml
Provides necessary default configuration for iMX RT106x/6ULL Ethernet driver.
This PR might not be passing some tests on `armv7a7-imx6ull-evk` without [https://github.com/phoenix-rtos/phoenix-rtos-lwip/pull/96](https://github.com/phoenix-rtos/phoenix-rtos-lwip/pull/96).
Part of [https://jira.phoenix-rtos.com/browse/RTOS-507](https://jira.phoenix-rtos.com/browse/RTOS-507).
-  https://github.com/phoenix-rtos/phoenix-rtos-lwip/pull/96
=>  _projects/(imx6ull, imxrt106x): Add config for iMX ENET driver

_projects/aarch64a53-zynqmp-qemu/board_config.h, _projects/aarch64a53-zynqmp-som/board_config.h, _projects/aarch64a53-zynqmp-zcu104/board_config.h
This change fixes values used to configure ZynqMP PS-PL AXI bus width
=> zynqmp: fix AXI width config

.github/actions/phoenix-build/action.yml, .github/actions/phoenix-runner/action.yml, .github/problem-matchers/sanitizer-errors.json, .github/workflows/_send_google_chat.yml, .github/workflows/ci-project.yml, .github/workflows/ci-release.yml, .github/workflows/ci-submodule.yml
- ci-release: use docker release tag for CI
- ci: make docker image tag parametrizable
Switch to composite action to dynamically choose docker image version.
Also: run docker in privileged mode.
- ci: remove "go to repo" button in google chat notification
- ci: remove obsolete secrets/outputs
- ci: fix ubsan problem matcher colored output
work around GH bug actions/runner#2341
CI-582, CI-390
=> ci: bulid/test release branches using release docker images
