_targets/build.project.armv7m7-imxrt106x
Majority of the changes in this script were made after checking correctness using shellcheck app.
=> imxrt106x: copy plo-ram*.img to _boot; clean up script.

_targets/build.project.armv7m7-imxrt106x, build.project
This PR should be merged after approving
- https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/155
- https://github.com/phoenix-rtos/phoenix-rtos-build/pull/34
- https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/74
=> build.project: allow to run b_build_project function from specific target build file

_targets/armv7m7-imxrt117x.plo, _targets/build.project.armv7m7-imxrt117x
=> Added imxrt117x project build

_targets/armv7a9-zynq7000.plo, _targets/build.project.armv7a9-zynq7000
This PR should be merged when the following PRs will be approved and added:
- https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/186
- https://github.com/phoenix-rtos/plo/pull/34
=> zynq7000: add new board to targets

scripts/qemu/ia32-generic-ata.sh, scripts/qemu/ia32-generic-rtl.sh, scripts/qemu/ia32-generic-vblk.sh, scripts/qemu/ia32-generic-vgpu.sh, scripts/qemu/ia32-generic-vnet.sh, scripts/qemu/ia32-generic.sh, scripts/qemu/riscv64-virt-vblk.sh, scripts/qemu/riscv64-virt-vgpu.sh, scripts/qemu/riscv64-virt-vnet.sh, scripts/qemu/riscv64-virt.sh
JIRA: PD-20
This PR fixes bugs mentioned in [previous PR](https://github.com/phoenix-rtos/phoenix-rtos-project/pull/53). The scripts were checked with shellcheck.
=> scripts/qemu: fixed bugs reported by shellcheck

.github/actions/phoenix-build/action.yml, .github/actions/phoenix-runner/action.yml, .github/workflows/ci.yml, _targets/build.project.ia32-generic, build.project
=> ci: add test runner job

_targets/build.project.armv7a7-imx6ull, _targets/build.project.armv7a9-zynq7000, _targets/build.project.armv7m7-imxrt106x, _targets/build.project.armv7m7-imxrt117x, _targets/build.project.host-pc, _targets/build.project.ia32-generic, _targets/build.project.riscv64-spike, _targets/build.project.riscv64-virt
JIRA: CI-48
This PR moves submodules to include most of the changes regarding new `Makefiles` in most of the submodules.
PR should verify if it compiles for all of the platforms.
=> makes: install binaries into rootfs by make rules

_targets/build.project.armv7a7-imx6ull, _targets/build.project.armv7m7-imxrt106x, _targets/build.project.armv7m7-imxrt117x, _targets/build.project.ia32-generic, _targets/build.project.riscv64-spike, _targets/build.project.riscv64-virt
=> build: ports: take CFLAGS and LDFLAGS from makefile

_targets/build.project.armv7m4-stm32l4x6
Need to be merge after https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/113
JIRA: ISC-105
=> stm32l4: Update stm32l4-multi driver name

_user/rotrectangle/Makefile, _user/rotrectangle/main.c
=> _user/rotrectangle: added user example - rotating rectangle program - draft

_user/rotrectangle/Makefile, _user/rotrectangle/main.c
Correct rotating rectangle program
Except for minor fixes:
Stack size for thread has been changed
Mutex functions has been added for better synchronization
Volatile prefix has been added for variables used in thread
JIRA: PD-119
=> _user/rotrectangle: correct rotating rectangle program

_user/voxeldemo/Makefile, _user/voxeldemo/main.c
https://user-images.githubusercontent.com/141153/122703660-62b34880-d252-11eb-8efb-51855b236c94.mp4
JIRA: RTOS-49
Voxel Space demo which is self contained and does not depend on external resources voxel terrain is procedurally generated.
=> _user/voxeldemo: Add Voxel Space example gfx demo

_targets/build.common.imxrt, _targets/build.project.armv7m7-imxrt106x, _targets/build.project.armv7m7-imxrt117x
Changes:
- make common shell's functions for imxrt family
- update build.project files for imxrt106x and imxrt117x
- add `b_dev_image` function to create artefacts for development purposes
- add `b_prod_image` function to create production artefacts
New development artefacts, based on imxrt106x platform:
- plo-script-armv7m7-imxrt106x-dev.img - file contains loader and user script
- script-armv7m7-imxrt106x-dev.plo - remote script
- script-kernel-app-armv7m7-imxrt106x.disk - file contains user script, kernel and applications
This changes allow increase development on imxrt targets using phoenix-rtos-loader.
JIRA: PD-122
=> _targets/imxrt: create artefacts and scripts for development

_user/voxeldemo/main.c
RTOS: 57
This PR adds double buffering to fix fickering on Cirrus adapter and enables to run demo on "any" graph video adapter which support 32bit true color.
Fixes flickering on cirrus.
=> _user/voxeldemo: Add double buffering and make run on "any" graph video adapter

busybox_config
JIRA: RTOS-59
It's needed for runnning BusyBox testsuite.
JIRA: RTOS-59
=> busybox_config: include busybox applet

_targets/build.project.armv7a9-zynq7000
At this stage, there is used only plo-ram-armv7a9-zynq700.img. After the last changes,
this image needs ramscript.plo.
JIRA: PD-151
=> _targets/zynq7000: create ramscript.plo

_targets/build.project.armv7m7-imxrt106x
JIRA: RTOS-21
This change amends itcm and dtcm maps sizes.
In my project I need more dtcm memory, which is not cachable for the usb stack. The whole set of programs including kernel uses 216 kB of dtcm and only 122 kB of itcm. This change would also be beneficial in the future, as we are planning to run more programs, which would also increase the kernel's dtcm usage.
Other memory maps must be updated in the same manner.
Additional PRs:
https://github.com/phoenix-rtos/plo/pull/114
https://github.com/phoenix-rtos/phoenix-rtos-hostutils/pull/26
=> imxrt106: Increase dtcm map size, decrease itcm map size

_targets/build.project.armv7a7-imx6ull, build.project, scripts/ia32-generic.sh
Few small changes needed for more robust project specification.
Also some small generic fixes smuggled.
=> Enhance `imx6ull` build script

.github/workflows/ci.yml
=> imxrt1064: add self-hosted runner

_targets/build.project.armv7m7-imxrt117x
JIRA: CI-92
_targets: imxrt117x: add building and installing tests
It's needed for imxrt117x target testing with gh-actions.
JIRA: CI-92
=> _targets: imxrt117x: add building and installing tests

_targets/build.project.riscv64-spike, _targets/build.project.riscv64-virt
allow RISCV_LOADER to be set when building risc-v targets
Documentation, including quickstarts needs to be updated. There could be possibility to run risc-v virt target using bbl loader. To allow that without changing file contents RISCV_LOADER variable shouldn't be redefined. I think for risc-v spike it's more flexible too.
JIRA: PD-206
=> _targets: allow RISCV_LOADER to be set when building risc-v targets

_targets/build.project.armv7a7-imx6ull
Add building for imx6ull.
Checkout plo and phoenix-rtos-kernel to branches where new version of plo is implemented.
**NOTE**: This version currently works only for Cortex-A architectures. Some additional work has to be done for the rest of the architectures.
JIRA: RTOS-121
=> imx6ull: build plo and phoenix*.disk image

docker-devel.sh
=> add script to run phoenixrtos/devel

_targets/build.project.armv7m4-stm32l4x6
=> stm32l4: Add dummyfs to multidrv

.gitmodules
=> .gitmodules: set feature/syspage branch for plo & phoenix-rtos-kernel

_targets/build.project.armv7a7-imx6ull
=> armv7a7-imx6ull: remove /etc/version creation

.gitmodules, _targets/build.common, _targets/build.project.armv7a7-imx6ull, _targets/build.project.armv7m4-stm32l4x6, _targets/build.project.ia32-generic
=> Added support for STM32. Submodule update

_targets/build.project.ia32-generic
=> _targets/ia32: for CONSOLE=serial use uart16550 instead of pc-tty

_targets/build.project.armv7m7-imxrt106x, _targets/build.project.armv7m7-imxrt117x
JIRA: CI-103
- waiting 2s after loading apps not before in user script
- add go! command to user script
- change imap memory for imxrt-multi to xip1 (imxrt117x and imxrt106x) as @gerard5 suggested
With this change and adding `go!` command to user script psh would be launched by default and test runner could interrupt `Waiting for input`. I propose doing it like in `armv7m7-imxrt106x` target, but I am not sure if there is a reason for the difference.
=> _targets: user script changes for imxrt117x and imxrt106x

_targets/build.project.armv7m7-imxrt106x
DONE: RTOS-152
_targets: imxrt106x: add go! command to user script 
Automatic starting psh after 2 seconds like in other targets.
=> _targets: imxrt106x: add go! command to user script

_targets/build.project.armv7a7-imx6ull, _targets/build.project.riscv64-spike, _targets/build.project.riscv64-virt
=> riscv: update building process

_targets/build.common, _targets/build.project.armv7a7-imx6ull, _targets/build.project.armv7m4-stm32l4x6, _targets/build.project.armv7m7-imxrt106x, _targets/build.project.ia32-generic, _targets/build.project.riscv64-spike, _targets/build.project.riscv64-virt
=> merge feature/syspage

_targets/build.project.armv7a9-zynq7000
_targets: zynq7000: place wait cmd before go!
It would be easier to load test binaries in CI process.
JIRA: CI-111
=> _targets: zynq7000: place wait cmd before go!

_targets/build.project.armv7m7-imxrt106x
DONE: RTOS-152
_targets: imxrt106x: restore go! command to user script 
Automatic starting psh after 2 seconds like in other targets. The feature was added a few commits before, but probably has been removed by accident.
=> _targets: imxrt106x: restore go! command to user script

_targets/build.common
=> _targets/common: calculate user script max size based on user script and kernel offset

_targets/build.project.armv7a9-zynq7000
_targets: add defuser hash for armv7a9-zynq7000 target
It's required for working psh login applet -> enabling test-auth.py
=> _targets: add defuser hash for armv7a9-zynq7000 target

_targets/build.project.armv7a9-zynq7000, _targets/build.project.armv7m4-stm32l4x6, _targets/build.project.armv7m7-imxrt106x, _targets/build.project.armv7m7-imxrt117x, _targets/build.project.ia32-generic
It reenable possibility to recreate image only without rebuild whole
system.
JIRA: ISC-129
Change allows to do `./phoenix-rtos-build/build.sh image` step alone, if everything is already build.
This change is useful while developing build system solutions, when replacing single binary, that was modified outside the build system.
Also it fixes regresion, as that was possible before.
=> _targets: Move b_mkscript_user to b_image_target

.github/workflows/ci.yml, _projects/build.project.armv7a9-zynq7000-qemu, _projects/build.project.armv7a9-zynq7000-zedboard, _targets/build.project.armv7a9-zynq7000, scripts/armv7a9-zynq7000.sh
- _projects: add separate bulding scripts for zynq7000 qemu and zedboard
- ci: split zynq7000 targets for building job
* phoenix-rtos-build da655d9...2ea2994 (1):
> armv7a9-zynq7000: add building host utils with phoenixd
* phoenix-rtos-devices da12595...c7499cc (3):
> zynq7000-flash/tests: update tests after changes in flashdrv
> zynq7000/flashdrv: apply libstorage interface
> zynq7000-flash/flashcfg: change sector erase size from 0x1000 to 0x10000 for Micron n25q128
* phoenix-rtos-doc db8a748...0ba0a43 (2):
> doc: update zynq7000 quickstarts and buiding chapter
> interrupt() correction
* phoenix-rtos-lwip 2a872e9...075e812 (3):
> wifi: retry to start AP on failure (max 5 times)
> wifi: fix resources cleanup on AP start failure
> port/threads: sys_thread_join fix
* …
=> split zynq7000 target into qemu and zedboard + update submodules

.github/workflows/ci-submodule.yml, .github/workflows/ci.yml
- ci: enable 'armv7a9-zynq7000-qemu' target testing
JIRA: CI-110
=> ci: enable 'armv7a9-zynq7000-qemu' target testing

_projects/build.project.armv7a9-zynq7000-qemu, _projects/build.project.armv7a9-zynq7000-zedboard, _targets/build.project.armv7a9-zynq7000
=> merge mtd interface & update zynq7000

_projects/armv7a9-zynq7000-zturn/build.project
=> zynq7000-zturn: declare partitions and rootfs for flash server

.github/workflows/ci-submodule.yml, .github/workflows/ci.yml, _targets/build.common, _targets/build.project.armv7a7-imx6ull, _targets/build.project.armv7a9-zynq7000, _targets/build.project.armv7m4-stm32l4x6, _targets/build.project.armv7m7-imxrt106x, _targets/build.project.armv7m7-imxrt117x, _targets/build.project.ia32-generic, _targets/build.project.riscv64-generic, scripts/armv7a9-zynq7000-qemu.sh, scripts/ia32-generic-qemu-test.sh, scripts/ia32-generic-qemu-virt.sh, scripts/ia32-generic-qemu.sh, scripts/riscv64-generic-qemu.sh, scripts/riscv64-generic-spike.sh
1. Every project has now its own directory for build artifacts  - _boot/$TARGET
2. Installed artifacts have generic names, e.g. plo.img, phoenix-kernel.elf, phoenix.img, phoenix.disk
[RTOS-199](https://jira.phoenix-rtos.com/browse/RTOS-199)
Existing projects will no longer build properly. They have to be adapted to the new structure.
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/120
https://github.com/phoenix-rtos/phoenix-rtos-hostutils/pull/38
https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/113
https://github.com/phoenix-rtos/plo/pull/181
=> Introduce separate build artifacts directory inside _boot/ for every project

_targets/build.project.armv7m7-imxrt106x
=> armv7m7-imxrt106x: Install user plo script inside boot directory

_projects/armv7a9-zynq7000-qemu/board_config.h, _projects/armv7a9-zynq7000-zedboard/board_config.h, _projects/armv7a9-zynq7000-zturn/board_config.h
Added default GPIO configuration for armv7a9-zynq7000 projects.
[JIRA: PP-46](https://jira.phoenix-rtos.com/browse/PP-46)
=> _projects/armv7a9-zynq7000: add GPIO configuration

_projects/armv7a9-zynq7000-qemu/board_config.h, _projects/armv7a9-zynq7000-zedboard/board_config.h
=> armv7a9-zynq-qemu,zedboard: Define uart pins

_projects/armv7a9-zynq7000-zedboard/build.project
- fix partition offset,
- update submodules,
PD-278
=> zedboard: fix fs partition offset & update submodules

_projects/armv7a9-zynq7000-qemu/board_config.h, _projects/armv7a9-zynq7000-zedboard/board_config.h, _projects/armv7a9-zynq7000-zturn/board_config.h
=> _projects/zynq7000: move qspi pin configuration to board_config.h

_projects/armv7a9-zynq7000-zedboard/build.project
- update plo and phoeni-rtos-devices
- use full memory size in zedboard
PD-278
=> update submodules & zedboard partitions layout

_projects/armv7a9-zynq7000-qemu/build.project, _projects/armv7a9-zynq7000-zedboard/build.project, _projects/armv7a9-zynq7000-zturn/build.project, _targets/build.project.armv7a9-zynq7000
- _projects: zynq7000-zedboard: wait before loading programs
- _targets: zynq7000: copy plo with debug symbols to _boot
JIRA: PD-296
- wait change:
During Zedboard testing plo will be loaded using gdb. We do not know what is present in flash, so it's better to interrupt waiting before kernel and app commands.
- copy change:
Required for loading plo using gdb
=> add required changes for Zedboard Test Runner

_projects/armv7a9-zynq7000-qemu/board_config.h, _projects/armv7a9-zynq7000-zedboard/board_config.h, _projects/armv7a9-zynq7000-zturn/board_config.h
PP-82
Adding missing defines to to `zynq-7000` targets.
=> projects/armv7a9-zynq7000: add UART16550 configuration to board_config.h

docker-devel.sh
- add --privileged arg to docker-devel script
- add mounting /dev/bus/usb in docker-devel script
- It's needed for using jlink tools.
- JIRA: RTOS-257
=> add args required for using jlink tools to docker-devel script

_projects/armv7a9-zynq7000-qemu/build.project, _projects/armv7a9-zynq7000-zedboard/build.project, _projects/armv7a9-zynq7000-zedboard/rootfs-overlay/etc/rc.psh
These changes are necessary to run `LONG_TESTS`.
RTOS-264
=> _projects/zedboard & qemu: increase rootfs partition and add posixsrv

_projects/ia32-generic-qemu/build.project, _targets/build.project.armv7m7-imxrt106x
- add mbedtls and azure sdk to ports config
- JIRA: PD-251
=> add mbedtls and azure sdk to ports config

_targets/build.common
=> build.common: Allow flags other than -x for apps

.github/workflows/ci-submodule.yml, .github/workflows/ci.yml
- ci: enable zynq7000-zedboard testing
- update submodules
- Testing more target architectures
- JIRA: PD-297
=> Enable zynq7000-zedboard CI

_projects/armv7a9-zynq7000-qemu/board_config.h, _projects/armv7a9-zynq7000-qemu/rootfs-overlay/etc/rc.psh, _projects/armv7a9-zynq7000-zedboard/board_config.h, _projects/armv7a9-zynq7000-zturn/board_config.h, _projects/ia32-generic-pc/board_config.h, _projects/ia32-generic-qemu/board_config.h, _projects/riscv64-generic-qemu/board_config.h, _projects/riscv64-generic-spike/board_config.h
- update _projects after changes in devices
- update submodules
=> Add klog to all architectures

_projects/armv7a9-zynq7000-qemu/board_config.h, _projects/armv7a9-zynq7000-zedboard/board_config.h, _projects/armv7a9-zynq7000-zturn/board_config.h
=> _projects: add I2C to zynq-7000 board_config files

.github/workflows/ci-submodule.yml, .github/workflows/ci.yml
=> ci: run tests on stm32l4 hardware

_targets/build.project.armv7m7-imxrt117x
Cause of removal:
The board configuration is already present in the header file: [`_projects/armv7m7-imxrt117x-evk/board_config.h`](https://github.com/phoenix-rtos/phoenix-rtos-project/blob/master/_projects/armv7m7-imxrt117x-evk/board_config.h) and per custom projects.
Updated submodule:
* plo dc68030...a680de9 (8):
> armv7m: Refactor exceptions implementation
> armv7m: Add exception dispatcher
> imxrt117x: Add custom FlexRAM memory maping
> imxrt: Replace UART_CONSOLE with UART_CONSOLE_PLO
> imxrt117x: Disable unused uart's
> imxrt117x: Add board_config.h to console setup
> imxrt10xx: Add board_config.h to console setup
> imxrt117x: Use default uart setup for imxrt1176-evk
JIRA: NIL-422
https://github.com/phoenix-rtos/plo/pull/240
=> imxrt117x: remove duplicated board config

docker-build.sh
This approach does not work due to building as root in docker
JIRA: RTOS-443
Now it works, but a little bit slowly.
=> docker-build.sh: temporary disable using tmpfs on MacOS

.github/workflows/ci-project.yml, .github/workflows/nightly-quick.yml
=> ci: separate scheduled ci-project workflow

README.md
=> README: add nightly badge

.github/workflows/nightly-quick.yml, .github/workflows/nightly.yml
=> ci: provide secrets for nightly workflows

_targets/build.project.ia32-generic
_targets: ia32-generic: increase rootfs size from 1.5x to 3x du
Enable more long tests.
The previous size was too small for busybox cp tests, when mbedtls tests were also imported
JIRA: CI-289
=> _targets: ia32-generic: increase rootfs size from 1.5x to 3x du

_user/hellocpp/Makefile, _user/hellocpp/main.cpp
project: add exmple of user app in cpp
Presenting C++ in our system
JIRA: RTOS-405
=> project: add exmple of user app in cpp

_projects/armv7a7-imx6ull-evk/build.project, _projects/armv7a7-imx6ull-evk/rootfs-overlay/etc/rc.psh, _targets/build.common, _targets/build.project.armv7a7-imx6ull
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/369
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/662
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/728
=> imx6ull-evk: add JFFS2 rootfs

_targets/build.common
Regression from cc18610789b4b833ae62d9f614c4f1ef2edf4ee3
Recently commit introduce error while creating images that wasn't catched with set -e, due to beinig inside test command. Not sure if we have a way to avoid those errors automaticially.
I also change TODO comment with reasonable explanation.
Not sure if dev images is still used, maybe it can be removed?
Eliminating bash errors.
=> _targets: Fix build error

.github/workflows/ci-project.yml, .github/workflows/ci-submodule.yml
=> ci: enable running tests on armv7a-imx6ull-evk target

docker-devel.sh
=> Enable docker devel to be run from any directory.

_projects/sparcv8leon3-gr716-mini/board_config.h, _projects/sparcv8leon3-gr716-mini/build.project, _targets/build.project.sparcv8leon3-gr716
=> add sparcv8leon3-gr716-mini project

.gitignore
* libphoenix 822d7df...481eeeb (1):
> errno: remove EDEADLK definition
* phoenix-rtos-doc f9284bd...42c1aa9 (2):
> coding: Update coding guidelines
> Update toolchains list
* phoenix-rtos-kernel b30747b...2fa06fd (8):
> lib: Add and use lib_strdup
> posix: implement dynamic fd table size
> posix: Change maxfd interpretation from "last index" to "table size"
> posix: Remove dead code
> posix.c: Partial code style fix
> proc_join: add deadlock check
> errno: add EDEADLK definition
> proc_join: fix race condition
* phoenix-rtos-ports afb3e77...a4f2248 (1):
> add fs_mark port
* phoenix-rtos-tests ab3ce19...1cb5b02 (2):
> trunner: run tests alphabetically
> phoenixd: change the way how plo USB connections are handled.
=> Submodule update

.github/actions/phoenix-build/action.yml
=> ci: set DEBUG variable to 1, when building

.github/actions/phoenix-runner/action.yml, .github/problem-matchers/sanitizer-errors.json, .github/workflows/_send_google_chat.yml, .github/workflows/ci-project.yml, .github/workflows/ci-submodule.yml, .github/workflows/ci.yml, .github/workflows/nightly-quick.yml, .github/workflows/nightly.yml
- ci: send google chat notification on failure
- ci: test runner: enable enhancements
- enable test results exporting
- gather and merge results
- report them as a separate check / in PRs
- ci: test: add sanitizer problem matchers
Fixes: phoenix-rtos/phoenix-rtos-project#797
- ci: fix workflow definition mistakes
- ci: switch to shorter job names
- submodule update
phoenix-rtos-tests 4e2f6dd..53877da
=> Test runner enhacements

.github/workflows/ci-project.yml
=>   ci: add armv7m7-imxrt105x-evk to build

_targets/build.project.sparcv8leon3-gr716
=> gr716: add bch generation to project build

.github/workflows/ci-project.yml, .github/workflows/ci-submodule.yml, scripts/ia32-generic-qemu-net.sh, scripts/ia32-generic-qemu-test.sh, scripts/ia32-generic-qemu-virt.sh, scripts/ia32-generic-qemu.sh
- ci: fix not always uploading test results
- ci: build host utils for host-generic-pc target
- scripts/ia32-generic: fix qemu disk definition
Use correct syntax to avoid annoying warning message regarding the RAW image
format.
JIRA: CI-334
=> fix qemu ia32 scripts + add hostutils CI build

.github/workflows/ci-project.yml, .github/workflows/ci-submodule.yml
For some targets hostutils are needed to prepare target image. Ensure they are always available.
JIRA: CI-334
=> ci: enable building host tools for all platforms

mtd-utils/build.sh
fix building zynq/ull targets on macOS after changes in phoenix-rtos-build/build.sh
JIRA: CI-340
=> mtd-utils: update build.sh to a new convention

docker-build.sh
=> docker-build.sh: pass LONG_TEST variable

.github/workflows/ci-submodule.yml
=> ci-submodule: add building imxrt105x-evk project

_user/hellocpp/Makefile
=> _user: fix linking C++ program

_targets/build.project.sparcv8leon3-gr716
=> gr716: use gr716-multi driver

.github/workflows/ci-project.yml, .github/workflows/ci-submodule.yml
=> ci: add building sparcv8leon3-gr716-mini project 

_projects/sparcv8leon3-gr716-mini/board_config.h
JIRA: RTOS-618
With the GR712RC, at least some driver code will be shared between the two targets, I don't want to define `SYSCLK_FREQ` in each driver twice. Also easier to change if needed.
=> gr716: define SYSCLK_FREQ in board config

_projects/armv7a7-imx6ull-evk/build.project, _projects/armv7m4-stm32l4x6-nucleo/build.project, _projects/armv7m7-imxrt105x-evk/build.project, _projects/armv7m7-imxrt106x-evk/build.project
JIRA: DEND-32
Disable WATCHDOG explicitly, which will be included in phoenix-rtos/phoenix-rtos-build#163
Currently nothing refreshing watchdog in phoenix-rtos-project.
It would be great if someone could check this changes on armv7a7-im6ull-evk and arm7m7-imxrt117x-evk
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/847
https://github.com/phoenix-rtos/plo/pull/293
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/453
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/163
=> _projects: disable WATCHDOG in projects

.github/workflows/ci-project.yml, .github/workflows/ci-submodule.yml, .github/workflows/lint.yml
- ci: lint: switch to clang-format-16
JIRA: CI-351
- ci: remove mail notification on failure
JIRA: CI-221
=> ci: remove mail notification & switch to clang-format-15 tool

docker-build.sh
=> docker-build: return to building as a host user

.github/workflows/ci-project.yml, .github/workflows/ci-submodule.yml
=> ci: add riscv64-generic-qemu project

_projects/armv7m4-stm32l4x6-nucleo/board_config.h
=> armv7m4: enable TTY_DMA

_projects/sparcv8leon3-gr716-mimas/board_config.h, _projects/sparcv8leon3-gr716-mimas/build.project, _projects/sparcv8leon3-gr716-mini/board_config.h, _projects/sparcv8leon3-gr716-mini/build.project, _targets/build.project.sparcv8leon3-gr716
=> add gr716-mimas project

_projects/sparcv8leon3-gr712rc-board/board_config.h, _projects/sparcv8leon3-gr712rc-board/build.project, _targets/build.project.sparcv8leon3-gr712rc
JIRA: RTOS-615
* libphoenix 993f5e7...8f30b74 (1):
> sparcv8leon3: add GR712RC target
* phoenix-rtos-build d2850d8...cf9c9a4 (1):
> add sparcv8leon3-gr712rc target
* phoenix-rtos-devices 552c3bb...3b6e4fd (4):
> tty/grlib-uart: support GR712RC
> tty: rename gr716-uart to grlib-uart
> _targets: add sparcv8leon3-gr712rc
> imxrt-flash: optimize opRead/opWrite add cpu yield
* phoenix-rtos-filesystems cc2e6a8...09a029e (2):
> _targets: add sparcv8leon3-gr712rc
> ext2: Ignore I/O errors when unmounting filesystem
* phoenix-rtos-kernel dcfb262...cf8714a (5):
> add GR712RC support, Gaisler cpu refactor
> add codespell_ignore
> proc: fix setting entry point in process_load
> vm/map: use PGHD_READ attr when mapping pages
> proc: Handle usleep(0) (yield)
* phoenix-rtos-tests c230f33...36b0b78 (1):
> …
=> add gr712rc target

_projects/sparcv8leon3-gr712rc-board/build.project, _projects/sparcv8leon3-gr712rc-board/rootfs-overlay/etc/rc.psh, _targets/build.project.sparcv8leon3-gr712rc
=> sparcv8leon3-gr712rc: add rootfs creation

_targets/build.project.armv7a9-zynq7000
***The second commit will be submodules update***
The file plo-gdb.elf is intended to be uploaded to RAM, that's why this file should be used.
This change will make CI flashing process common with other targets, where plo is uploaded first.
=> _targets: zynq7000: copy plo-ram as plo-gdb file

_projects/sparcv8leon3-gr712rc-board/board_config.h, _projects/sparcv8leon3-gr716-mimas/board_config.h, _projects/sparcv8leon3-gr716-mimas/build.project, _projects/sparcv8leon3-gr716-mini/board_config.h, _targets/build.project.sparcv8leon3-gr712rc, _targets/build.project.sparcv8leon3-gr716
JIRA: RTOS-704
Add necessary defines for `grlib-multi` driver, use `grlib-multi` on GR712RC.
=> sparcv8leon3: adapt to use of amba pnp

_targets/build.common, _targets/build.project.armv7m7-imxrt117x
Align offsets and enable using second, virtual memory bank 
It allows to run a phoenix based project from virtual bank (i.e. any memory offset) without modifying user script.
=> firmware_upg_imxrt117x

_projects/riscv64-generic-qemu/board_config.h, _projects/riscv64-generic-qemu/rootfs-overlay/etc/rc.psh, _projects/riscv64-generic-spike/board_config.h, _projects/riscv64-generic-spike/build.project, _targets/build.project.riscv64-generic, scripts/riscv64-generic-qemu.sh, scripts/riscv64-generic-spike.sh
- update `board_config`
- modify RISC-V build scripts to use PLO
- update OpenSBI to version 1.4
- remove `riscv-pk` - BBL bootloader no longer used
**Update submodules:**
* libphoenix 1fa7f4e...86334a3 (3):
> Change libphoenix initialization
> string: remove memsetw
> stdlib/strtod: remove duplicate set errno
* phoenix-rtos-devices 07ea8e3...6bc928b (5):
> storage/virtio-blk: add support for MBR and rootfs
> libmbr: remove
> uart16550/riscv: fix warning
> uart16550/riscv: use info from board_config
> stm32l4-multi: Add RNG driver
* phoenix-rtos-doc 17d2e17...0e50130 (1):
> quickstart: update riscv64 documentation
* phoenix-rtos-kernel 0890d1b...a1980f4 (9):
> riscv64: refactor kstack handling
> riscv64: rename status register bits
> riscv64/sbi: use SBI calls in ver 0.2+
> riscv64: …
=> riscv64: plo support

_user/serverdemo/Makefile, _user/serverdemo/main.c
=> _user: Add example server - serverdemo

docker-build.sh
Add support for .docker_build_img config files for docker-build.sh
JIRA: CI-344
=> build: Add support for different docker images

.gitmodules
Submodule was removed from repo but not from `.gitmodules`
=> .gitmodules: remove riscv-pk

_projects/sparcv8leon3-gr712rc-board/board_config.h, _projects/sparcv8leon3-gr716-mimas/board_config.h, _projects/sparcv8leon3-gr716-mimas/build.project, _projects/sparcv8leon3-gr716-mini/board_config.h
=> add DMA configuration for `gr716-mimas`

_user/serverdemo/main.c
Breaking msg API changes in `phoenix-rtos-kernel`:
- `oid` is moved from `i.<type>` to common message part
- `const` is added to input data pointer - **this introduces warnings in some functions!**
- `err` is moved from `o.<type>` to `o` struct
- `mtGetAttrAll` msg type is added, allowing the caller to get all file attributes through one message. In this case `struct _attrs` should be allocated and pointer to it should be written into `msg.o.data` (and sizeof to `msg.o.size`). https://github.com/phoenix-rtos/libphoenix/pull/351 provides `_phoenix_initAttrsStruct` that initializes errors in `struct _attrs`.
Convention for the return value is following:
- If the server doesn't at all provide support for `mtGetAttrAll` message, it will return negative value in `msg.o.err` field. Other fields …
=> Change msg API

_projects/armv7a7-imx6ull-evk/build.project, _projects/riscv64-generic-qemu/build.project, _projects/riscv64-generic-spike/build.project, _projects/sparcv8leon3-gr716-mimas/build.project, _projects/sparcv8leon3-gr716-mini/build.project
JIRA: DEND-366
https://github.com/phoenix-rtos/plo/pull/320
=> _projects: Adapt to PLO device selection

_targets/build.project.armv7m4-stm32l4x6, _targets/build.project.armv7m7-imxrt105x, _targets/build.project.armv7m7-imxrt106x, _targets/build.project.armv7m7-imxrt117x, _targets/build.project.sparcv8leon3-gr716
* phoenix-rtos-build 77c4211...2aa1919 (4):
> Introduce HAVE_MMU in target Makefile
> target: pass address of NOMMU kernel from project
> target: Fix assignments
> add setup and test execution script (https://github.com/phoenix-rtos/phoenix-rtos-project/pull/182)
JIRA: DEND-306
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/183
=> _targets: Adapt to passing KERNEL_PHADDR on NOMMU

.github/workflows/ci-project.yml, .github/workflows/ci-submodule.yml
=> ci: remove decrease aslr entropy before testing and building

scripts/ia32-generic-qemu-test.sh
=> scripts: add cpu_reset flag to ia32-generic-qemu tests related script

_projects/riscv64-generic-qemu/board_config.h, _projects/riscv64-generic-spike/board_config.h, _targets/build.project.riscv64-generic
=> riscv64: update configuration

_projects/armv7a7-imx6ull-evk/build.project, _projects/armv7m7-imxrt106x-evk/board_config.h, _projects/armv7m7-imxrt117x-evk/board_config.h
=> _project: setup targets for PPP and LwiP usage

_targets/build.common
When supplying paths for `app` and `blob` commands:
- relative path _path_ resolves to _build/_arch_/prog.stripped/_path_
- absolute path _path_ resolves to _fs/_arch_/root/_path_
JIRA: NIL-571
=> _targets: Add 'blob' command

README.md
=> README.md: change redirection to docs subdomain

_projects/riscv64-generic-qemu/build.project, _projects/riscv64-generic-spike/build.project, _targets/build.project.riscv64-generic, scripts/riscv64-generic-qemu.sh, scripts/riscv64-generic-spike.sh
- use Phoenix SBI
* phoenix-rtos-kernel 85d8038...963bf56 (1):
> riscv64: align ustack in hal_cpuCreateContext
* plo 087fb36...5fa5d6f (4):
> riscv-sbi/exceptions: handle empty mtval register
> riscv-sbi: handle multicore systems
> riscv-sbi: add legacy put/getchar extensions
> riscv-sbi: implement basic SBI for RISC-V
=> riscv64: use Phoenix SBI

_projects/armv8r52-mps3an536-qemu/board_config.h, _projects/armv8r52-mps3an536-qemu/build.project, _targets/build.project.armv8r52-mps3an536, scripts/armv8r52-mps3an536-qemu.sh
JIRA: RTOS-875
- add `armv8r52-mps3an536-qemu` target
* libphoenix 85ceda0...685bf80 (1):
> arch: add ARMv8-R support
* phoenix-rtos-build f5caf89...a30f728 (2):
> target/armv8r.mk: add mtune flag
> add support for ARMv8 Cortex-R52 (MPS3 AN536 platform)
* phoenix-rtos-devices 040859c...4d8edcc (1):
> add armv8r52-mps3an536 uart driver
* phoenix-rtos-doc 46b7ea9...0d4de8c (2):
> quickstart: add armv8r52-mps3an536-qemu target
> libc: update cond and mutex functions documentation
* phoenix-rtos-filesystems a9a5302...ae4483a (2):
> _targets: add armv8r52-mps3an536
> meterfs: Fix error reporting from read
* phoenix-rtos-kernel 8c260ab...764a9df (3):
> proc/process_load (NOMMU): fix phdr size check
> add support for ARMv8 Cortex-R52 (MPS3 AN536 platform)
> imxrt/timer: Fix …
=> add armv8r52-mps3an536-qemu target, update submodules

.github/actions/phoenix-build/action.yml, .github/actions/phoenix-runner/action.yml
Pull times (from one sample):
- build: 21s (dockerhub), 20s (ghcr)
- devel: 26s (dockerhub), 26s (ghcr)
Done due to Docker Hub Pull Rate Limit (100 pulls per 6 hours)
=> ci: use docker images hosted by ghcr.io

_projects/riscv64-noelv-fpga/build.project
It's necessary to use elf file as the SBI payload may need to be loaded to a completely different address than the SBI itself.
=> _projects/riscv64-noelv: copy sbi to boot directory

_projects/sparcv8leon3-generic-qemu/board_config.h, _projects/sparcv8leon3-generic-qemu/build.project, _targets/build.project.sparcv8leon3-generic, scripts/sparcv8leon3-generic-qemu.sh
JIRA: RTOS-887
- add `sparcv8leon3-generic-qemu` target
* libphoenix 3375557...49f0324 (2):
> arch: add sparcv8leon3-generic target
> locale: Fix incomplete locale.h
* phoenix-rtos-build f995fe1...9acad4d (2):
> add sparcv8leon3-generic target
> sparcv8leon3: add LEON3_USE_PWR define
* phoenix-rtos-devices 3d18d6b...e279ca4 (1):
> _targets: add sparcv8leon3-generic target
* phoenix-rtos-doc 0d4de8c...e7909f6 (6):
> docs: fix render mathematical expressions
> fix README.md warnings
> add build workflow
> fix bullet list elements not printed when starting with %
> quickstart/gr712rc: fix index links
> quickstart: add sparcv8leon3-gr712rc-board target
* phoenix-rtos-filesystems 816a9c6...ac000e1 (1):
> _targets: add sparcv8leon3-generic target
* phoenix-rtos-kernel …
=> add sparcv8leon3-generic-qemu target

_targets/build.project.sparcv8leon3-gr716
JIRA: RTOS-848
plo has grown a bit and some targets may not fit it before user script. This change moves user script and kernel offsets. 
Necessary for:
- https://github.com/phoenix-rtos/plo/pull/315
=> _targets/sparcv8leon3-gr716: Increase user script and kernel offset

scripts/sparcv8leon3-generic-qemu-test.sh
=> scripts: add sparcv8leon3-generic-qemu-test script

_targets/build.project.armv7m4-stm32l4x6
Map contains area of OTP, ADC reference values and Option Bytes
stm32l4-multi uses this map for ADC measurement, OTP read/write and Option Bytes read.
=> _targets: Add missing map for stm32l4x6

_projects/armv7a7-imx6ull-evk/rootfs-overlay/etc/rc.psh, _projects/armv7a9-zynq7000-qemu/rootfs-overlay/etc/rc.psh, _projects/armv7a9-zynq7000-zedboard/rootfs-overlay/etc/rc.psh, _projects/armv7a9-zynq7000-zturn/rootfs-overlay/etc/rc.psh, _projects/ia32-generic-pc/rootfs-overlay/etc/rc.psh, _projects/ia32-generic-qemu/rootfs-overlay/etc/rc.psh, _projects/riscv64-generic-qemu/rootfs-overlay/etc/rc.psh
JIRA: RTOS-924
Any code dependent on `/tmp` being persistent across reboots will be invalid after this change (though such code shouldn't exist in the first place)
=> _projects: add /tmp ramdisk on big targets

.gitmodules
=> Remove opensbi submodule

.github/workflows/ci-project.yml, .github/workflows/ci-submodule.yml
- ci: add building sparcv8leon3-gr716-mimas
- ci: add building sparcv8leon3-gr712rc-board
- ci: add building armv8m33-mcxn94x-frdm
- ci: add building armv8r52-mps3an536-qemu
To catch potential regression
JIRA: CI-498
=> ci: add building new targets

_targets/armv7a7/imx6ull/build.project, _targets/armv7a9/zynq7000/build.project, _targets/ia32/generic/build.project, _targets/ia32/generic/nvm.yaml, _targets/riscv64/generic/build.project, _targets/riscv64/generic/nvm.yaml
=> build: fix generated rootfs size

_targets/ia32/generic/nvm.yaml
Loader size has increased with addition of new plo commands
JIRA: RTOS-906
=> _targets/ia32-generic: increase plo partition size

.github/workflows/ci-project.yml, .github/workflows/ci-submodule.yml, .github/workflows/lint.yml
- ci: use shellcheck on all files with *sh shebang
- ci: support running on ubuntu-24.04 image
=> ci: support running on ubuntu-24.04 image

.github/actions/phoenix-build/action.yml, .github/actions/phoenix-runner/action.yml, .github/workflows/ci-project.yml, .github/workflows/ci-submodule.yml
=> ci: remove obsolete SYSPAGE build option

.github/workflows/ci-project.yml, .github/workflows/ci-submodule.yml
- ci: add running tests on sparcv8leon3-generic-qemu
- ci: add building sparcv8leon3-generic-qemu
=> ci: add sparcv8leon3-generic-qemu

docker-devel.sh
Entrypoint in phoenixrtos/devel image is bash -l -c which passes additional arguments to bash not to the program rum by bash.
JIRA: RTOS-952
Before: `./docker-devel.sh ./phoenix-rtos-tests/runner.py --target armv7a9-zynq7000-qemu -t phoenix-rtos-tests/sys` didnt work, `./docker-devel.sh "./phoenix-rtos-tests/runner.py --target armv7a9-zynq7000-qemu -t phoenix-rtos-tests/sys"` had to be passed.
=> !docker-devel.sh: pass arguments in double quotes

_projects/armv7a9-zynq7000-qemu/user.plo.yaml
JIRA: CI-494
- https://github.com/phoenix-rtos/phoenix-rtos-build/pull/212
=> armv7a9-zynq7000-qemu: add `blob` plo command example usage

_projects/sparcv8leon-generic-qemu/board_config.h, _projects/sparcv8leon-gr712rc-board/board_config.h, _projects/sparcv8leon-gr716-mimas/board_config.h, _projects/sparcv8leon-gr716-mini/board_config.h
JIRA: RTOS-969
Update timer IRQ definitions
Update submodules:
* phoenix-rtos-devices 407a22e...3a4fd5d (1):
> imxrt-multi: CM4_RUN_CORE returns EALREADY if core is running
* phoenix-rtos-doc a91f64e...5e5addf (3):
> building: correct the reference project description
> fix casing
> correct contest
* phoenix-rtos-kernel dbbddd8...c47c66d (4):
> hal/sparcv8leon: implement hp timer
> hal/sparcv8leon/irqmp: set broadcast bits for appropriate irqs
> hal/sparcv8leon/irqamp: remove explicit interrupt clearing
> syscalls: make nsleep handle unslept time correctly
* phoenix-rtos-ports 549e10b...aa8d22d (1):
> Add coreMQTT library
* phoenix-rtos-posixsrv d7ffb8d...4525014 (1):
> make isatty() set correct errno for special devices
* phoenix-rtos-tests c510830...216255e (3):
> libc: split tests for …
=> sparcv8leon/board_config: update timer IRQ definitions, update submodules

_targets/armv7m7/imxrt117x/nvm.yaml
Increase memory for plo partition by increasing the next partition's (user) offset.
needed by https://github.com/phoenix-rtos/plo/pull/732
=> _targets/imxrt117x: increase memory for plo

.github/workflows/ci-project.yml, .github/workflows/ci-submodule.yml, .gitignore, _projects/sparcv8leon-generic-qemu/board_config.h, _projects/sparcv8leon-gr712rc-board/board_config.h, _projects/sparcv8leon-gr712rc-board/build.project, _projects/sparcv8leon-gr716-mimas/board_config.h, _projects/sparcv8leon-gr716-mini/board_config.h, _projects/sparcv8leon-gr740-mini/board_config.h, _projects/sparcv8leon-gr740-mini/build.project, _projects/sparcv8leon-gr740-mini/rootfs-overlay/etc/rc.psh, _targets/sparcv8leon/generic/nvm.yaml, _targets/sparcv8leon/gr712rc/build.project, _targets/sparcv8leon/gr712rc/nvm.yaml, _targets/sparcv8leon/gr712rc/preinit.plo.yaml, _targets/sparcv8leon/gr712rc/user.plo.yaml, _targets/sparcv8leon/gr740/build.project, _targets/sparcv8leon/gr740/nvm.yaml, _targets/sparcv8leon/gr740/preinit.plo.yaml, _targets/sparcv8leon/gr740/user.plo.yaml
- https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/389
- https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/632
- https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1260
- https://github.com/phoenix-rtos/libphoenix/pull/401
- https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/143
- https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/230
- https://github.com/phoenix-rtos/plo/pull/375
- https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/532
- https://github.com/phoenix-rtos/phoenix-rtos-build/pull/222
- https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/143
=> add support for gr740, update sparc targets configuration

_projects/sparcv8leon-gr740-mini/rootfs-overlay/etc/rc.psh
=> sparcv8leon-gr740-mini: mount dummyfs in /tmp

.github/workflows/ci-project.yml, .github/workflows/ci-submodule.yml, _projects/riscv64-noelv-fpga/board_config.h, _projects/riscv64-noelv-fpga/build.project, _projects/riscv64-noelv-fpga/rootfs-overlay/etc/rc.psh, _projects/sparcv8leon-gr716-mini/board_config.h, _targets/riscv64/noelv/build.project, _targets/riscv64/noelv/nvm.yaml, _targets/riscv64/noelv/preinit.plo.yaml, _targets/riscv64/noelv/user.plo.yaml
- add support for flash on `riscv64-noelv-fpga`
* libphoenix 706e829...cd16bdb (4):
> arch/sparcv8leon: increase PATH_MAX and NAME_MAX values
> !unistd.h: move _POSIX_VDISABLE from termios.h
> unistd: define POSIX constants
> posix: create header with POSIX defined limits
* phoenix-rtos-build 8c6ec6f...a17b459 (2):
> scripts: add script to create boot layout for ZynqMP
> toolchain: add toolchain for AArch64
* phoenix-rtos-devices eeaa59b...78a4a91 (1):
> flashdrv: set cache policy to write-through in spimctrl driver
* phoenix-rtos-doc f5ce6ea...e204f8d (4):
> quickstart: add riscv64-noelv-fpga target
> mcxn947-evk: add quickstart
> Remove .DS_Store
> quickstart: add sparcv8leon-gr740-mini target
* phoenix-rtos-filesystems 893b63b...ba9b965 (1):
> …
=> riscv64-noelv: flash memory support, update submodules

_projects/armv7r5f-zynqmp-qemu/board_config.h, _projects/armv7r5f-zynqmp-qemu/build.project, _projects/armv7r5f-zynqmp-qemu/nvm.yaml, _targets/armv7r5f/zynqmp/build.project, _targets/armv7r5f/zynqmp/nvm.yaml, _targets/armv7r5f/zynqmp/preinit.plo.yaml, _targets/armv7r5f/zynqmp/user.plo.yaml, scripts/armv7r5f-zynqmp-qemu.sh
=> Add armv7r5f-zynqmp-qemu target

_projects/aarch64a53-zynqmp-qemu/board_config.h, _projects/aarch64a53-zynqmp-som/board_config.h, _projects/aarch64a53-zynqmp-zcu104/board_config.h
Added an option to route console UART in zynqmp via PL subsystem
=> zynqmp: routing console via pl

_projects/aarch64a53-zynqmp-zcu104/board_config.h, _projects/aarch64a53-zynqmp-zcu104/user.plo.yaml
- upgrade submodule to pull new changes:
* phoenix-rtos-devices 04e4310...423c512 (1):
- zynqmp: add CAN driver
- add ZCU104 board CAN interface configuration and add CAN driver to plo script for this board
=> zynqmp: add CAN driver

_targets/armv7a7/imx6ull/build.project, _targets/armv7a9/zynq7000/build.project, _targets/armv7m4/stm32l4x6/build.project, _targets/armv7m7/imxrt105x/build.project, _targets/armv7m7/imxrt106x/build.project, _targets/armv7m7/imxrt117x/build.project, _targets/armv8m33/mcxn94x/build.project, _targets/armv8r52/mps3an536/build.project, _targets/ia32/generic/build.project, _targets/riscv64/generic/build.project, _targets/riscv64/noelv/build.project, _targets/sparcv8leon/generic/build.project, _targets/sparcv8leon/gr712rc/build.project, _targets/sparcv8leon/gr716/build.project, _targets/sparcv8leon/gr740/build.project
Submodule update:
* phoenix-rtos-build 707f7ae...319b16d (1):
> makes: fix DEP_LIB typo in static-lib.mk
* phoenix-rtos-devices 871a2db...2f69b72 (3):
> sensors: add support for generic EKF state sensor
> sensors: add support for differential barometer
> zynqmp: add uart16550 support
* phoenix-rtos-doc a5015b6...dd5c2cf (2):
> ci: lint: use `fail_level` input for reviewdog
> ci: migrate to actions based on node20
* phoenix-rtos-ports 2321b08...6cc3c34 (3):
> lighttpd: lighttpd 1.4.79
> add CoreMark-PRO port
> build.sh: update HOST and HOST_TARGET assignments
* phoenix-rtos-tests cd9e07d...f318084 (1):
> trunner: increase delayafterterminate for processDUT
=> update submodules, add Coremark(-PRO) port configuration

_projects/aarch64a53-zynqmp-som/board_config.h, _projects/aarch64a53-zynqmp-som/user.plo.yaml
Changes:
- added i2c config in aarch64a53-zynqmp-som project
- added i2c driver to user.plo.yaml
JIRA: PP-289
=> zynqmp: add aarch64a53-zynqmp-som i2c config

.github/actions/phoenix-build/action.yml, .github/actions/phoenix-runner/action.yml, .github/workflows/ci-project.yml, .github/workflows/ci-submodule.yml
- ci: build aarch64a53-zynqmp-qemu target
- ci: switch to beta images (test gcc 14.2)
=> ci: switch to gcc 14.2

_targets/aarch64a53/zynqmp/build.project, _targets/build.common, _targets/ia32/generic/build.project
Needed for https://github.com/phoenix-rtos/phoenix-rtos-build/pull/184
=> prepare shell scripts for `nounset` bash option

_projects/riscv64-noelv-fpga/build.project
JIRA: RTOS-1070
Submodule update:
* phoenix-rtos-devices 1effaf1...1f9cdcb (11):
> usbacm: suppress snprintf format warning
> usbacm: update the dev refcnt on failure
> usbacm: fix use-after-free due to incorrect idtree_alloc error value check
> umass: access requests in FIFO order
> umass: use strncpy
> umass: remove intermediate buffer
> umass: fix umass_mountFromDev error paths
> umass/srv: wait for rootfs instead of console
> umass: decrease number of worker threads and make it configurable
> usbacm: use idtree for device id allocation
> usbacm: remove unused drvport, rename usbacm_freeAll to _usbacm_freeAll
* phoenix-rtos-kernel 7db978d...41afdc9 (1):
> pmap: fix TLB flush address in _pmap_halMapInternal
* plo 30ca8d0...3b7c091 (6):
> riscv64: add ram-storage driver to PLO_ALLDEVICES …
=> build: set PLO_DEVICES for riscv64-noelv-fpga project, update submodules

.github/actions/phoenix-build/action.yml, .github/actions/phoenix-runner/action.yml
- x ] My change requires a change to the documentation.
=> ci: switch to stable images

docker-build.sh
=> docker-build: increase size of tmpfs for macOS build

.github/workflows/ci-project.yml
JIRA: CI-575
Done in the same way as the rootfs to avoid loosing permissions when packing to zip. This small issue hasn't been seen before, because in CI binaries like phoenixd/psu are taken from docker.
=> ci-project: tar boot directory before upload

.github/actions/phoenix-build/action.yml, .github/actions/phoenix-runner/action.yml
When running docker manually - we need to reflect the host paths (no Path translation is done in the runner).
This should fix the annotations (problem-matchers file-match).
JIRA: CI-582
=> ci: fix in-docker paths

scripts/armv7a9-zynq7000-qemu-test.sh
JIRA: CI-397
Due to poor performance under QEMU when SMP kernel is enabled, change device tree used by QEMU in test scenerio to a single-core system. It was mentioned originally on : https://github.com/phoenix-rtos/phoenix-rtos-project/commit/90c36f8f09e347419a886c0ea2bbfc6423329226
=> scripts: armv7a9-zynq7000-qemu-test use proper dtb file
